### ISSUE TITLE
crash  No implementation found for void com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator()

### ISSUE THREAD

**Issue by daijiangping** [f111fei/react-native-unity-view#130]
java.lang.Error: FATAL EXCEPTION [main]
Unity version : 2018.3.6f1
Device model : samsung SM-G9650
Device fingerprint: samsung/star2qltezc/star2qltechn:9/PPR1.180610.011/G9650ZCU5CSH6:user/release-keys

Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator() (tried Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator and Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator__)
at com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator(Native Method)
at com.unity3d.player.UnityPlayer.resume(Unknown Source:23)
at com.reactnative.unity.view.UnityViewManager.onHostResume(UnityViewManager.java:101)
at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:184)
at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:646)
at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:565)
at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:521)
at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:105)
at com.facebook.react.ReactActivity.onResume(ReactActivity.java:64)
at com.vesal.kangfuxunlian.MainActivity.onResume(MainActivity.java:62)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
at android.app.Activity.performResume(Activity.java:7611)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3984)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4024)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:6990)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by AniG007** [comment]
I'm also getting the same error. Let me know if you have a fix for this

**Comment by axinyue** [comment]
I find this problem. unity export android project will auto build java api.so you can't use old version override "unity-classes.jar" file.
