### ISSUE TITLE
BuildConfig already present during Android compilation

### ISSUE THREAD

**Issue by im-aditya** [f111fei/react-native-unity-view#30]
I am getting this compile time error on Android. Any help ?

```
D8: Program type already present: com.mycompany.projectname.BuildConfig

> Task :app:transformDexArchiveWithDexMergerForDebug FAILED
```

**Comment by im-aditya** [comment]
I tried changing the package name of the Unity project to something other then my react native project. Basically my react native project's package is _com.mycompany.projectname_ and I named the unity project to _com.mycompany.projectname.unity_ 

After that, the above error disappeared but the app crashes on runtime:

```
E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText [text:  : null}]' to a 'RCTView')
        at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:279)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:56)
        at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:482)
        at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by im-aditya** [comment]
This also got resolved, so closing it.
